server:
  port: 8090

spring:
  application:
    name: spring-security

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security_db?createDatabaseIfNotExist=true
    username: root
    password:
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  application:
    secret: secret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_keysecret_key
    token-prefix: Bearer
    validity-period: 300 #in seconds
    authorization-header: Authorization
